# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'book_win.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(804, 187)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(700, 140, 93, 29))
        self.pushButton.setStyleSheet("font: 12pt \"黑体\";")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(11, 11, 71, 41))
        self.label.setStyleSheet("font: 12pt \"黑体\";")
        self.label.setObjectName("label")
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        self.radioButton_3.setGeometry(QtCore.QRect(323, 54, 72, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(Form)
        self.radioButton_4.setGeometry(QtCore.QRect(166, 54, 72, 19))
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(Form)
        self.radioButton_5.setGeometry(QtCore.QRect(9, 54, 72, 19))
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup.addButton(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(Form)
        self.radioButton_6.setGeometry(QtCore.QRect(480, 54, 57, 19))
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup.addButton(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(Form)
        self.radioButton_7.setGeometry(QtCore.QRect(323, 80, 57, 19))
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup.addButton(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(Form)
        self.radioButton_8.setGeometry(QtCore.QRect(480, 80, 110, 19))
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup.addButton(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(Form)
        self.radioButton_9.setGeometry(QtCore.QRect(166, 80, 87, 19))
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup.addButton(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(Form)
        self.radioButton_10.setGeometry(QtCore.QRect(9, 80, 57, 19))
        self.radioButton_10.setObjectName("radioButton_10")
        self.buttonGroup.addButton(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(Form)
        self.radioButton_11.setGeometry(QtCore.QRect(637, 54, 57, 19))
        self.radioButton_11.setObjectName("radioButton_11")
        self.buttonGroup.addButton(self.radioButton_11)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 60, 20))
        self.label_2.setStyleSheet("font: 12pt \"黑体\";")
        self.label_2.setObjectName("label_2")
        self.phone_num_le = QtWidgets.QLineEdit(Form)
        self.phone_num_le.setGeometry(QtCore.QRect(10, 140, 271, 31))
        self.phone_num_le.setObjectName("phone_num_le")
        self.train_name = QtWidgets.QLineEdit(Form)
        self.train_name.setGeometry(QtCore.QRect(320, 140, 251, 31))
        self.train_name.setPlaceholderText("")
        self.train_name.setObjectName("train_name")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(320, 110, 391, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 12pt \"黑体\";")
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 140, 93, 29))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.confirm)
        self.pushButton_2.clicked.connect(Form.cancel)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "确认"))
        self.label.setText(_translate("Form", "坐席"))
        self.radioButton_3.setText(_translate("Form", "二等座"))
        self.radioButton_3.setProperty("val", _translate("Form", "O"))
        self.radioButton_4.setText(_translate("Form", "一等座"))
        self.radioButton_4.setProperty("val", _translate("Form", "M"))
        self.radioButton_5.setText(_translate("Form", "商务座"))
        self.radioButton_5.setProperty("val", _translate("Form", "9"))
        self.radioButton_6.setText(_translate("Form", "无座"))
        self.radioButton_6.setProperty("val", _translate("Form", "WZ"))
        self.radioButton_7.setText(_translate("Form", "软卧"))
        self.radioButton_7.setProperty("val", _translate("Form", "4"))
        self.radioButton_8.setText(_translate("Form", "硬卧/二等卧"))
        self.radioButton_8.setProperty("val", _translate("Form", "3"))
        self.radioButton_9.setText(_translate("Form", "高级软卧"))
        self.radioButton_9.setProperty("val", _translate("Form", "6"))
        self.radioButton_10.setText(_translate("Form", "动卧"))
        self.radioButton_10.setProperty("val", _translate("Form", "F"))
        self.radioButton_11.setText(_translate("Form", "硬座"))
        self.radioButton_11.setProperty("val", _translate("Form", "1"))
        self.label_2.setText(_translate("Form", "手机号"))
        self.label_3.setText(_translate("Form", "列车车次(请用英文逗号隔开；例如G12,G13)"))
        self.pushButton_2.setText(_translate("Form", "取消"))

