# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'query_win.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1093, 600)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStatusTip("")
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.start_date_de = QtWidgets.QDateEdit(self.widget)
        self.start_date_de.setCalendarPopup(True)
        self.start_date_de.setObjectName("start_date_de")
        self.gridLayout_3.addWidget(self.start_date_de, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 6, 2, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setStyleSheet("font: 12pt \"华文细黑\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("font: 12pt \"华文细黑\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("font: 12pt \"华文细黑\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("font: 12pt \"华文细黑\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.adult_tk_cb = QtWidgets.QRadioButton(self.widget)
        self.adult_tk_cb.setStyleSheet("font: 10pt \"Agency FB\";")
        self.adult_tk_cb.setObjectName("adult_tk_cb")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.adult_tk_cb)
        self.gridLayout_3.addWidget(self.adult_tk_cb, 1, 4, 1, 1)
        self.nromal_tk_cb = QtWidgets.QRadioButton(self.widget)
        self.nromal_tk_cb.setStyleSheet("font: 10pt \"Agency FB\";")
        self.nromal_tk_cb.setObjectName("nromal_tk_cb")
        self.buttonGroup.addButton(self.nromal_tk_cb)
        self.gridLayout_3.addWidget(self.nromal_tk_cb, 1, 3, 1, 1)
        self.to_station_cb = QtWidgets.QComboBox(self.widget)
        self.to_station_cb.setEditable(True)
        self.to_station_cb.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.to_station_cb.setObjectName("to_station_cb")
        self.gridLayout_3.addWidget(self.to_station_cb, 0, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 5, 2, 1)
        self.from_station_cb = QtWidgets.QComboBox(self.widget)
        self.from_station_cb.setEditable(True)
        self.from_station_cb.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.from_station_cb.setObjectName("from_station_cb")
        self.gridLayout_3.addWidget(self.from_station_cb, 0, 1, 1, 1)
        self.gridLayout_3.setRowStretch(0, 2)
        self.gridLayout_3.setRowStretch(1, 4)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tickets_tv = QtWidgets.QTableView(self.widget_2)
        self.tickets_tv.setObjectName("tickets_tv")
        self.gridLayout_2.addWidget(self.tickets_tv, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 5)
        self.gridLayout.setRowStretch(1, 11)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.query_tk)
        self.pushButton_2.clicked.connect(Form.book_tk)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.start_date_de.setDisplayFormat(_translate("Form", "yyyy-MM-dd"))
        self.pushButton_2.setText(_translate("Form", "抢票"))
        self.label_5.setText(_translate("Form", "      类型"))
        self.label_3.setText(_translate("Form", "出发地"))
        self.label_2.setText(_translate("Form", "      目的地"))
        self.label_4.setText(_translate("Form", "出发日"))
        self.adult_tk_cb.setText(_translate("Form", "成人票"))
        self.adult_tk_cb.setProperty("q_value", _translate("Form", "ADULT"))
        self.nromal_tk_cb.setText(_translate("Form", "学生票"))
        self.nromal_tk_cb.setProperty("q_value", _translate("Form", "0X00"))
        self.pushButton.setText(_translate("Form", "查询"))

